### ISSUE TITLE
Thread safe?

### ISSUE THREAD

**Issue by rsagner** [miyako/4d-plugin-xslt#3]
Hi Miyako and thanks for providing this plugin.

Is the plugin in master branch thread-safe? When testing with 4D v17 (tested 17.0 HF4 and 17r6) it says it is not but since you have an old branch named unthread-safe I just want to make sure I have not missed anything.

Best,

Rikard / Metodika - Sweden

**Comment by miyako** [comment]
I think I created the branch but never finished working on it.

work is needed to make the code thread safe.

http://www.xmlsoft.org/threads.html

**Comment by miyako** [comment]
done in v2.

https://miyako.github.io/2019/09/17/4d-plugin-xslt.html

notice the command syntax is changed for simplicity and object support.
